// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.3
// source: profanity.proto

package profanity

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProfanityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ProfanityRequest) Reset() {
	*x = ProfanityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profanity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfanityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfanityRequest) ProtoMessage() {}

func (x *ProfanityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profanity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfanityRequest.ProtoReflect.Descriptor instead.
func (*ProfanityRequest) Descriptor() ([]byte, []int) {
	return file_profanity_proto_rawDescGZIP(), []int{0}
}

func (x *ProfanityRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ProfanityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ProfanityResponse) Reset() {
	*x = ProfanityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profanity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfanityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfanityResponse) ProtoMessage() {}

func (x *ProfanityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profanity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfanityResponse.ProtoReflect.Descriptor instead.
func (*ProfanityResponse) Descriptor() ([]byte, []int) {
	return file_profanity_proto_rawDescGZIP(), []int{1}
}

func (x *ProfanityResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_profanity_proto protoreflect.FileDescriptor

var file_profanity_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x61, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x70, 0x72, 0x6f, 0x66, 0x61, 0x6e, 0x69, 0x74, 0x79, 0x22, 0x26, 0x0a, 0x10,
	0x50, 0x72, 0x6f, 0x66, 0x61, 0x6e, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x65, 0x78, 0x74, 0x22, 0x27, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x66, 0x61, 0x6e, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x32, 0x5a, 0x0a,
	0x09, 0x50, 0x72, 0x6f, 0x66, 0x61, 0x6e, 0x69, 0x74, 0x79, 0x12, 0x4d, 0x0a, 0x10, 0x73, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x66, 0x61, 0x6e, 0x69, 0x74, 0x79, 0x12, 0x1b,
	0x2e, 0x70, 0x72, 0x6f, 0x66, 0x61, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x61,
	0x6e, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x66, 0x61, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x61, 0x6e, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_profanity_proto_rawDescOnce sync.Once
	file_profanity_proto_rawDescData = file_profanity_proto_rawDesc
)

func file_profanity_proto_rawDescGZIP() []byte {
	file_profanity_proto_rawDescOnce.Do(func() {
		file_profanity_proto_rawDescData = protoimpl.X.CompressGZIP(file_profanity_proto_rawDescData)
	})
	return file_profanity_proto_rawDescData
}

var file_profanity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_profanity_proto_goTypes = []interface{}{
	(*ProfanityRequest)(nil),  // 0: profanity.ProfanityRequest
	(*ProfanityResponse)(nil), // 1: profanity.ProfanityResponse
}
var file_profanity_proto_depIdxs = []int32{
	0, // 0: profanity.Profanity.sensor_profanity:input_type -> profanity.ProfanityRequest
	1, // 1: profanity.Profanity.sensor_profanity:output_type -> profanity.ProfanityResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profanity_proto_init() }
func file_profanity_proto_init() {
	if File_profanity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_profanity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfanityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profanity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfanityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_profanity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profanity_proto_goTypes,
		DependencyIndexes: file_profanity_proto_depIdxs,
		MessageInfos:      file_profanity_proto_msgTypes,
	}.Build()
	File_profanity_proto = out.File
	file_profanity_proto_rawDesc = nil
	file_profanity_proto_goTypes = nil
	file_profanity_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfanityClient is the client API for Profanity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfanityClient interface {
	SensorProfanity(ctx context.Context, in *ProfanityRequest, opts ...grpc.CallOption) (*ProfanityResponse, error)
}

type profanityClient struct {
	cc grpc.ClientConnInterface
}

func NewProfanityClient(cc grpc.ClientConnInterface) ProfanityClient {
	return &profanityClient{cc}
}

func (c *profanityClient) SensorProfanity(ctx context.Context, in *ProfanityRequest, opts ...grpc.CallOption) (*ProfanityResponse, error) {
	out := new(ProfanityResponse)
	err := c.cc.Invoke(ctx, "/profanity.Profanity/sensor_profanity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfanityServer is the server API for Profanity service.
type ProfanityServer interface {
	SensorProfanity(context.Context, *ProfanityRequest) (*ProfanityResponse, error)
}

// UnimplementedProfanityServer can be embedded to have forward compatible implementations.
type UnimplementedProfanityServer struct {
}

func (*UnimplementedProfanityServer) SensorProfanity(context.Context, *ProfanityRequest) (*ProfanityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SensorProfanity not implemented")
}

func RegisterProfanityServer(s *grpc.Server, srv ProfanityServer) {
	s.RegisterService(&_Profanity_serviceDesc, srv)
}

func _Profanity_SensorProfanity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfanityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfanityServer).SensorProfanity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profanity.Profanity/SensorProfanity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfanityServer).SensorProfanity(ctx, req.(*ProfanityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Profanity_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profanity.Profanity",
	HandlerType: (*ProfanityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sensor_profanity",
			Handler:    _Profanity_SensorProfanity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profanity.proto",
}
